version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: lumen_backend
    restart: unless-stopped
    # Pasa el archivo .env físico al contenedor
    env_file:
      - .env
    # No necesitamos exponer el puerto 3000 al mundo exterior,
    # Nginx (frontend) se comunicará con él internamente.

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: lumen_frontend
    restart: unless-stopped
    ports:
      - "81:80" # Expone el puerto 80 al internet
    depends_on:
      - backend