server {
    # Nginx INTERNAMENTE sigue escuchando en el puerto 80
    listen 80;
    server_name localhost;

    # 1. Sirve la aplicación React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Si no encuentra un archivo, devuelve el index.html de React
        try_files $uri $uri/ /index.html;
    }

    # 2. Atrapa todo lo que empiece con /api y lo manda a Fastify
    location /api {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Aumentar límites para subida de archivos pesados (PDFs)
        client_max_body_size 20M;

        # SSE / streaming: sin buffer para que los eventos lleguen en tiempo real
        proxy_buffering      off;
        proxy_read_timeout   300s;
        proxy_send_timeout   300s;
    }
}
